### ISSUE TITLE
Not parsing all server query responses correctly

### ISSUE THREAD

**Issue by StelStelox** [ayan4m1/minestat-es#3] opened 2024-09-27 00:09 UTC
One of the projects uses your library. But some servers in minecraft, which proxy the server through cloudflare, do not see the server status
https://github.com/AuroraTeam/Launcher/blob/44564e9c7864a996376dfb2c8d55b2a866158e09/src/main/scenes/ServersList.ts#L35C28-L35C62
![image](https://github.com/user-attachments/assets/0e9a5aa9-a102-4100-aa7f-4cd82e3865b9)
![image](https://github.com/user-attachments/assets/9e4e0518-be0f-46b5-bb50-dcae49e090f9)

**Comment by StelStelox** [comment] 2024-09-27 00:09
![image](https://github.com/user-attachments/assets/ac88c486-3182-41f0-9383-780c4da71e97)

**Comment by ayan4m1** [comment] 2024-09-28 02:42
Sorry, I'm having a very hard time understanding your issue. The first screenshot of JSON - where is that coming from? What is the context for this JSON? Also, what is the context of the second screenshot? It doesn't really tell me anything, I need to see the actual result from the fetchServerInfo promise.

To be clear, what I need are specifics for this scenario:

* What version of the library are you using? `npm ls minestat-es`
* What outputs are you expecting from fetchServerInfo? Provide a JSON object.
* What outputs are you actually getting from fetchServerInfo? Provide a JSON object.

Also, why is there a warning exclamation triangle next to the SRV record in your DNS screenshot? What does it tell you if you hover over / click on that?

**Comment by StelStelox** [comment] 2024-09-28 16:15
The launcher uses JSON to specify the path to the client libraries, as well as to specify the address of the game server, more details here https://docs.aurora-launcher.ru/basic/clients.html#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F . So the client part of the launcher uses your library in version 1.1.7, the problem is that the developer of the launcher himself cannot give a specific answer why, when proxy through the server, Cloudflare does not want to display the status not through ip:port and through A and SRV records (I checked on server monitoring, they see the server status). About the exclamation mark in DNS records Cloudfalre complains that SRV reveals the IP of the VDS server. About fetchServerInfo it is no longer used anywhere and pings servers independently

**Comment by JoCat** [comment] 2024-09-28 23:24
It looks like the problem may be on the server side or a flaw in the script.
![image](https://github.com/user-attachments/assets/0957134e-1400-4ad7-b546-872199723fec)

By the way, another issue I wanted to mention but didn't have time to, is the requirement to specify the “_minecraft._tcp” subdomain to allow SRV writes. This is not mentioned in the Readme, and it is not handled in any way in the code. You need to pick one of the options and fix it.

**Comment by ayan4m1** [comment] 2024-09-29 14:49
@JoCat Yes, that could certainly be an issue with the server. It could be caused by CloudFlare too, but I don't plan on supporting CloudFlare explicitly if they do some weird munging of the packets for Minecraft traffic.

The error you screenshotted is thrown when we receive less than 6 bytes back in response to the `0xfe, 0x01` preamble. That indicates that we got some invalid/incomprehensible reply from the server. Look into [this code](https://github.com/ayan4m1/minestat-es/blob/main/src/index.ts#L111-L118) for more debugging help - log out that `info` variable to see what the server is actually returning.

> By the way, another issue I wanted to mention but didn't have time to, is the requirement to specify the “_minecraft._tcp” subdomain to allow SRV writes. This is not mentioned in the Readme, and it is not handled in any way in the code. You need to pick one of the options and fix it.

Not sure what this is saying. Are you asking for the library to prepend `_minecraft._tcp` to the `hostname` parameter for SRV lookups? The tone of this message comes across as very disrespectful and arrogant to me, can you please clarify what you are trying to say here?

**Comment by JoCat** [comment] 2024-09-29 20:44
> Are you asking for the library to prepend `_minecraft._tcp` to the `hostname` parameter for SRV lookups?

Yeah, that's an option.

> The tone of this message comes across as very disrespectful and arrogant to me, can you please clarify what you are trying to say here?

Disrespect or arrogance is out of the question. I just wanted to mention that SRV records have a certain format, but your code or documentation does not take this into account in any way.

**Comment by ayan4m1** [comment] 2024-09-29 21:33
@JoCat Sorry, I had assumed it would be obvious that it would pass the string directly to the SRV resolver, and that the user would be prefixing `_minecraft._tcp.` in a real world scenario. I'll update the documentation and prepend the string if it's not already the start of the hostname string and release a v1.2.0 in the near future.

As to the actual issue reported here, please let me know when you've inspected the `info` variable and can see the bytes that are coming back from the server.

**Comment by JoCat** [comment] 2024-09-29 21:48
The first log is the output of the `raw` variable
Second - variable `info`

![image](https://github.com/user-attachments/assets/ce78f91c-26e6-4b80-acbc-2c9c8c91cd37)

**Comment by JoCat** [comment] 2024-09-29 22:02
I think I've realized what the error is, [your delimiters are counted by 3 zeros](https://github.com/ayan4m1/minestat-es/blob/6e6685fcecc525828e94270f034624c2c37e9892/src/index.ts#L110), although the correct way is 2 (I took the information from [wiki.vg](https://wiki.vg/Server_List_Ping#Server_to_client)) and if you make this change - everything will work.
![image](https://github.com/user-attachments/assets/a9b38f68-3796-4ab5-8933-a20caf53d228)

**Comment by JoCat** [comment] 2024-09-29 23:23
Implemented a more correct algorithm for reading a package based on information from wiki.vg

```ts
if (raw[0] !== 0xff) {
  return resolveOffline(
    new Error('Got invalid packet from Minecraft server!')
  );
}

// get usefull data from buffer and swap bytes (convert big endian to little endian for reading)
const infoBuffer = Buffer.alloc(raw.readInt16BE(1) * 2, 0, 'binary');
// Copy data into buffer
raw.copy(infoBuffer, 0, 3);
// swap bytes (convert big endian to little endian for reading)
infoBuffer.swap16();

// read buffer to string
const info = infoBuffer.toString('utf16le').split('\x00');

if (info.length < 6) {
  return resolveOffline(
    new Error('Got invalid reply from Minecraft server!')
  );
}

// attempt to parse data from server
const version = info[2];
const motd = info[3];
const players = parseInt(info[4], 10);
const maxPlayers = parseInt(info[5], 10);
```

Example of work:

![image](https://github.com/user-attachments/assets/c880c56f-d300-4b25-8723-e5e915a8b7f1)

**Comment by JoCat** [comment] 2024-09-30 00:09
I made a [fork](https://github.com/AuroraTeam/minestat-es) to test my concept. Everything seems to work, the only thing is that due to a small change in the parsing logic, the tests that catch the parsing error will need to be updated. If there are any changes or requirements from your side, please let me know. I will try to make them as soon as possible. Or you can use the sample code I posted above and refine it yourself.

**Comment by ayan4m1** [comment] 2024-09-30 01:49
I'm working with the code you've provided, but my "valid parse" test case is broken at the moment and I don't have any more time this weekend for personal projects. I'll try to take a look this week and get something merged in.

The byte you had to change in the tests, that was captured from a real server so it should be correct.

**Closed as completed** 2024-09-30 02:45 UTC
Labels: bug

**Comment by ayan4m1** [comment] 2024-09-30 02:47
@JoCat Please update to 2.1.0 and let me know if you continue to have issues. Thanks for your contribution.

**Comment by JoCat** [comment] 2024-09-30 15:03
> The byte you had to change in the tests, that was captured from a real server so it should be correct

strange, it seems that the packet is either longer (several bytes are missing, it seems to be in MOTD), or there is a wrong packet length specified in principle
